name = "album-github-worker"
main = "src/index.js"
compatibility_date = "2026-03-08"

[vars]
GITHUB_OWNER = "ZTRCOMPANY1"
GITHUB_REPO = "album-storage"
GITHUB_BRANCH = "main"
APP_NAME = "Nosso Álbum"
PUBLIC_MEDIA_BASE = "https://raw.githubusercontent.com/ZTRCOMPANY1/album-storage/main"
